[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm run railway:start"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10 