[build]
builder = "nixpacks"
buildCommand = "npm install --legacy-peer-deps && npm run build"
nixpacksNodeVersion = "20.11.0"

[deploy]
startCommand = "npm run railway:start"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100 