[build]
builder = "nixpacks"
buildCommand = "npm ci --legacy-peer-deps"
nixpacksNodeVersion = "20.11.0"

[deploy]
startCommand = "npm run railway:start"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100 